// Code generated by sqlc-gen-go-dynamic. DO NOT EDIT.

package db

import (
	"context"
	"github.com/mpyw/sqlc-gen-go-dynamic/dyn"
)

const searchUsersSQL = `select u.id, u.name
from users u
where 1 = 1
  /*%if activeOnly*/ and u.status = sqlc.arg('status') /*%end*/
  /*%if minAge != null*/ and u.age >= sqlc.arg('min_age') /*%end*/
  /*%if ids != null*/ and u.id in (sqlc.slice('ids')) /*%end*/
  /*%for c in conds*/ and (u.name like sqlc.arg('c.name') or u.status = sqlc.arg('c.status')) /*%end*/
order by /*%if byName*/ u.name, /*%end*/ u.id`

var searchUsersTemplate = dyn.MustParse(searchUsersSQL, "postgresql")

type SearchUsersParams struct {
	ActiveOnly bool
	Status     string
	MinAge     *int32
	Ids        []int64
	Conds      []SearchUsersCond
	ByName     bool
}

type SearchUsersCond struct {
	Name   string
	Status string
}

// TemplateScope names the fields as the template does.
func (p SearchUsersParams) TemplateScope() map[string]any {
	return map[string]any{
		"activeOnly": p.ActiveOnly,
		"status":     p.Status,
		"minAge":     p.MinAge,
		"min_age":    p.MinAge,
		"ids":        p.Ids,
		"conds":      p.Conds,
		"byName":     p.ByName,
	}
}

type SearchUsersRow struct {
	ID   int64
	Name string
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	stmt, err := searchUsersTemplate.Build(arg)
	if err != nil {
		return nil, err
	}
	rows, err := q.db.QueryContext(ctx, stmt.SQL, stmt.Args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
